### ISSUE TITLE
Add `keep_attrs` parameter to `pyramid_reproject`

### ISSUE THREAD

**Issue by maxrjones** [carbonplan/ndpyramid#103]
https://github.com/carbonplan/ndpyramid/pull/102 updated the demo notebook to only rely on utilities within ndpyramid. However, the output data currently doesn't work with the [maps demo](https://github.com/carbonplan/maps) because one of the attributes uses NaN, which is not valid JSON. The full set of attrs for this variable is as follows:

```
        "0/climate/.zattrs": {
            "AREA_OR_POINT": "Area",
            "STATISTICS_MAXIMUM": 34.099998474121,
            "STATISTICS_MEAN": NaN,
            "STATISTICS_MINIMUM": -46.095998535156,
            "STATISTICS_STDDEV": NaN,
            "_ARRAY_DIMENSIONS": [
                "band",
                "month",
                "y",
                "x"
            ],
            "coordinates": "spatial_ref"
        },
```

I think this opens a broader question though of whether we should add a `keep_attrs` parameter to the `pyramid_reproject` function for conveniently removing attributes from all resampled dataarrays. This seems more useful than checking for JSON compliance, since it is common for resampling operations to change the statistics and make these attributes obsolete.

**Comment by andersy005** [comment]
@maxrjones, i'm curious.... why did we remove the manual setting of metadata and encoding via `set_zarr_encoding()` function?

**Comment by maxrjones** [comment]
> @maxrjones, i'm curious.... why did we remove the manual setting of metadata and encoding via `set_zarr_encoding()` function?

It is redundant after https://github.com/carbonplan/ndpyramid/pull/31
