### ISSUE TITLE
ModuleNotFoundError("No module named \'ESMF\'") on dask workers

### ISSUE THREAD

**Issue by TomNicholas** [carbonplan/ndpyramid#126]
This is probably not specific to ndpyramid but I'm asking here because you guys are most likely to have run into this before.

I'm having an issue getting xESMF to run on dask workers on a distributed cluster at NCAR.

Basically running in the notebook I can execute xESMF (it's being called from `ndpyramid.pyramid_reproject`) just fine, but running the same function on a distributed PBSCluster using `dask.delayed` errors, with this written into the worker logs.

```
2024-04-24 22:49:46,781 - distributed.worker - WARNING - Compute Failed Key: process_polygon-94b7ebbe-df42-488b-b85b-0de0d2935ea5 Function: process_polygon args: ('000', '01') kwargs: {} Exception: 'ModuleNotFoundError("No module named \'ESMF\'")'
```

I've tried using dask's [plugins](https://distributed.dask.org/en/latest/plugins.html#built-in-scheduler-plugins) `PipInstallPlugin` and `CondaInstallPlugin` to manually install `xesmf` but neither of them make any difference.

Any ideas appreciated!

**Comment by TomNicholas** [comment]
Adding `job_script_prologue=['conda activate kerchunk3.9'],` to the `PBSCluster` call (where `kerchunk3.9` is the name of my conda environment that I'm successfully using within the notebook) didn't help either.

**Comment by maxrjones** [comment]
I'm curious where `ndpyramid.pyramid_reproject` is calling xESMF? That function should only be using rioxarray/rasterio/gdal. `ndpyramid.pyramid_regrid` is the option that uses xESMF.

**Comment by andersy005** [comment]
@TomNicholas, 

can you confirm that your client and workers are running in the same environment? 

on the client, what is the output of 

```python
import sys
print(sys.executable)
```

and then for the workers, what is the output of 

```python
import dask_jobqueue 
cluster = dask.jobqueue.PBSCluster(....)
print(cluster.job_script())
```

**Comment by TomNicholas** [comment]
Thanks both of you.

> I'm curious where ndpyramid.pyramid_reproject is calling xESMF? That function should only be using `rioxarray/rasterio/gdal`. `ndpyramid.pyramid_regrid` is the option that uses xESMF.

@maxrjones you're right it was `pyramid_regrid`.


I also just tried adding 
```python
job_script_prologue=['module load esmf', 'conda activate kerchunk3.9'],
```
to the cluster initialization, but that causes a different error
```
kwargs: {} Exception: "VersionMismatch('ESMF installation version 8.5.0, ESMPy version 8.4.2')"
```

> can you confirm that your client and workers are running in the same environment?
>
> on the client, what is the output of

`/glade/work/tnicholas/conda-envs/kerchunk3.9/bin/python`

> and then for the workers, what is the output of

The job_script for my cluster is now

```
#!/usr/bin/env bash

#PBS -N dask-worker
#PBS -q casper
#PBS -A P93300670
#PBS -l select=1:ncpus=1:mem=25GB
#PBS -l walltime=24:00:00
#PBS -e /glade/work/tnicholas/dask-workers/
#PBS -o /glade/work/tnicholas/dask-workers/
module load esmf
conda activate kerchunk3.9
/glade/work/tnicholas/conda-envs/kerchunk3.9/bin/python -m distributed.cli.dask_worker tcp://128.117.208.100:38905 --name dummy-name --nthreads 1 --memory-limit 23.28GiB --nanny --death-timeout 60 --local-directory /glade/work/tnicholas/dask-workers --interface ext
```

(before it was the same just without the `module load esmf` or `conda activate kerchunk3.9`.

**Comment by andersy005** [comment]
Thank you for sharing these, @TomNicholas! they look okay :). i have an account on NCAR machines, and i'm going to see if i can set up a a reproducer. 

 
> job_script_prologue=['module load esmf', 'conda activate kerchunk3.9'],

hmmm.... i didn't think this was necessary. but let me check

**Comment by andersy005** [comment]
@TomNicholas, something strange is going on on your end. i just ran [this notebook](https://gist.github.com/andersy005/4a55cb5834dbe658312b27bd3438ce8f) on derecho, and as you can see i didn't get the error you got:

https://github.com/carbonplan/ndpyramid/assets/13301940/d96f76af-2604-42d1-bd14-9dc3a5132562

**Comment by TomNicholas** [comment]
Thank you @andersy005 ! Let me try running your notebook...

**Comment by TomNicholas** [comment]
@

**Comment by TomNicholas** [comment]
(misclick)

@andersy005 I actually can't even import `ncar_jobqueue`

```
FileNotFoundError: [Errno 2] No such file or directory: '/glade/scratch/tnicholas'

During handling of the above exception, another exception occurred:

PermissionError                           Traceback (most recent call last)
Cell In[2], line 2
      1 import ndpyramid
----> 2 import ncar_jobqueue
      3 import dask
      4 from distributed import Client

File /glade/work/tnicholas/conda-envs/kerchunk3.9/lib/python3.9/site-packages/ncar_jobqueue/__init__.py:6
      3 """ Top-level module for ncar-jobqueue. """
      4 from pkg_resources import DistributionNotFound, get_distribution
----> 6 from . import config
      7 from .cluster import NCARCluster
      9 try:

File /glade/work/tnicholas/conda-envs/kerchunk3.9/lib/python3.9/site-packages/ncar_jobqueue/config.py:49
     46 destination_path = destination_dir / config_data_file_path.parts[-1]
     48 ensure_file(source=config_data_file_path, destination_path=destination_path)
---> 49 configure(destination_path)

File /glade/work/tnicholas/conda-envs/kerchunk3.9/lib/python3.9/site-packages/ncar_jobqueue/config.py:36, in configure(destination_path)
     34     if directory and isinstance(directory, str):
     35         full_path = dask.config.expand_environment_variables(directory)
---> 36         pathlib.Path(full_path).mkdir(parents=True, exist_ok=True)
     37 dask.config.update(
     38     dask.config.get('jobqueue'), dask.config.expand_environment_variables(original_data)
     39 )
```

Does yours have local changes to avoid the fact that `scratch` no longer exists?

**Comment by andersy005** [comment]
my bad.. i forgot to note that i had to make that change. yes, you need to update `~/.config/dask/ncar-jobqueue.yaml`

two changes:


1) the paths 

- log-directory: '/glade/derecho/scratch/${USER}/dask/logs'
- local-directory: '/glade/derecho/scratch/${USER}/dask/local-dir'

2) comment the `interface` as well 



```yaml
    name: dask-worker-derecho
    cores: 128 # Total number of cores per job
    memory: '235GB' # Total amount of memory per job
    processes: 32 # Number of Python processes per job
    
    #interface: ext # Network interface to use like eth0 or ib0
    queue: main
    walltime: '01:00:00'
    resource-spec: select=1:ncpus=128:mpiprocs=128:mem=235GB
    log-directory: '/glade/derecho/scratch/${USER}/dask/logs'
    local-directory: '/glade/derecho/scratch/${USER}/dask/local-dir'
```

**Comment by TomNicholas** [comment]
Thanks.

So your notebook works. And it still works when I set up a cluster on Casper the way I was doing (using this function I got from Matt).

```python
def get_ClusterClient(memory="25GB", project='P93300670', walltime='06:00:00', interface='lo'):
    """return client and cluster"""
    cluster = PBSCluster(
        cores=1,
        memory=memory,
        processes=1,
        queue='casper',
        local_directory=f'/glade/work/{USER}/dask-workers',
        log_directory=f'/glade/work/{USER}/dask-workers',
        resource_spec=f'select=1:ncpus=1:mem={memory}',
        project=project,
        walltime=walltime,
        interface=interface, # try 'lo', 'mgt', 'ext', 'eno2'
        job_script_prologue=['module load esmf', 'conda activate kerchunk3.9'],
    )

    jupyterhub_server_name = os.environ.get('JUPYTERHUB_SERVER_NAME', None)
    dashboard_link = 'https://jupyterhub.hpc.ucar.edu/stable/user/{USER}/proxy/{port}/status'
    if jupyterhub_server_name:
        dashboard_link = (
            'https://jupyterhub.hpc.ucar.edu/stable/user/'
            + '{USER}'
            + f'/{jupyterhub_server_name}/proxy/'
            + '{port}/status'
        )
    dask.config.set({'distributed.dashboard.link': dashboard_link})

    # Set the environment for Dask workers
    #dask.config.set({"distributed.worker.env": "kerchunk3.9"})
    
    client = Client(cluster)#, environment='kerchunk3.9')
    return cluster, client
```
```python
cluster, client = get_ClusterClient(walltime='24:00:00', interface='ext')
```

Which leaves me confused as to why my more complicated pipeline doesn't work 😭 I'll have to get back to you once I have some more idea of what the relevant difference is

**Comment by andersy005** [comment]
> Which leaves me confused as to why my more complicated pipeline doesn't work 😭 I'll have to get back to you once I have some more idea of what the relevant difference is

that's interesting... yeah, let me know how it goes.  do you have this complicated pipeline in a public repo on GitHub? i'd be happy to take a look or try to reproduce on NCAR systems.

**Comment by matt-long** [comment]
Perhaps related?
https://github.com/JiaweiZhuang/xESMF/issues/55#issuecomment-514298498

**Comment by andersy005** [comment]
good point, @matt-long. @TomNicholas, in my notebook, i'm not using any of the system modules (e.g. `esmf`)--everything is self-contained in the conda environment-- so, i'm wondering if somewhere in your configuration you have system modules that are messing your environment? so, i would check the output of `module list` to see which modules you have loaded.

**Comment by TomNicholas** [comment]
@andersy005 I was able to reproduce my error - wrapping your example in `dask.delayed` is enough to cause the `ModuleNotFoundError`. Let me know if you are able to reproduce the error with this notebook

https://gist.github.com/TomNicholas/560824d602b698e1d43dd781d05533e8

Any ideas why that might be the case? 😕

**Comment by negin513** [comment]
Thanks @TomNicholas for bringing this up to my attention. This is how I spin up my desk cluster and this worked for me now: 
https://gist.github.com/negin513/7351fc35f676d11790319b879d3abffd

**Comment by negin513** [comment]
The reason behind the failure was that, by default, PBS does not propagate environment variables to the jobs. This means that in your dask cluster created using PBS, the environment variables (including `ESMF_MKFILE`) are not propagated and are automatically available. 

There are two solutions @TomNicholas can use:

1) By adding `-V` in your PBS job, you can propagate all the environment variables from head node to your jobs. In the context of a Dask cluster configured via `PBSCluster`, this is done by including `job_extra=['-V']` in your cluster configuration. For example: 

```
# Create a PBS cluster object
cluster = PBSCluster(
    job_name = 'dask-wk23-hpc',
    cores = 1,
    memory = '4GiB',
    processes = 1,
    local_directory = '/local_scratch/pbs.$PBS_JOBID/dask/spill',
    resource_spec = 'select=1:ncpus=1:mem=4GB',
    queue = 'casper',
    walltime = '30:00',
    interface = 'ext',
    job_extra_directives=['-V']
)  
```

2) Alternatively, you can use  specify `job_script_prologue` argument to load your conda environment as follows: 
```
job_script_prologue = ['module load conda', 'conda activate npl-2024a', 'source ~/.bashrc']
```
and use it when creating `PBSCluster` object. 

Both solutions work and are shown here: https://gist.github.com/negin513/7351fc35f676d11790319b879d3abffd 


psst: In this case there is also another third solution that is not elegant, but that is a story for another day. 😉

**Comment by TomNicholas** [comment]
Suggestion (1) seems to be working for me at scale, thank you so much @negin513 !
