### ISSUE TITLE
[Support,Feature] How to revert from pyramid tiles to complete dataset?

### ISSUE THREAD

**Issue by meteoDaniel** [carbonplan/ndpyramid#37]
Dear @ndpyramid Team, 

I am really happy to see such a nice code about pyramids in xarray. I have implement a very similar way to chunk netcdf on my own. 
Actually I want to move from a netcdf4 store to a zarr store. For this purpose I need to revert the batching into the tiles. 

I have opened a stackoverflow thread [here](https://stackoverflow.com/questions/70952226/how-to-merge-different-shaped-netcdf4-files). 

I hope you can help me to find a proper way to revert the pyramid representation into one array.

**Comment by jhamman** [comment]
Have you tried using Xarray's [combine_by_coords](https://docs.xarray.dev/en/latest/generated/xarray.combine_by_coords.html) function? This could be a natural way to stitch tiles back together.

**Comment by meteoDaniel** [comment]
@jhamman , combine_by_coords needs a fixed dimension to concatenate the arrays along. 

I have found another way using the origin grid dimension and the same where statement to define the indices to write at. This works for me. 

Thanks 
Daniel
