### ISSUE TITLE
Example in README fails with datatree=0.0.5

### ISSUE THREAD

**Issue by observingClouds** [carbonplan/ndpyramid#39]
Hi,
I got attracted to this package by [your blog](https://carbonplan.org/blog/maps-library-release) and want to try it out for my own data. I thought the example on the README would be a good starting point to familiarise with the package. Unfortunately, I got an error when executing this:

**Minimal example**
```python
import xarray as xr
import rioxarray
from ndpyramid import pyramid_coarsen, pyramid_reproject

# load a sampel xarray.Dataset
ds = xr.tutorial.load_dataset('air_temperature')

# make a coarsened pyramid
pyramid = pyramid_coarsen(ds, factors=[16, 8, 4, 3, 2, 1], dims=['lat', 'lon'], boundary='trim')
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/envs/ndpyramid/lib/python3.10/site-packages/ndpyramid/core.py", line 51, in pyramid_coarsen
    pyramid[skey] = ds.coarsen(**kwargs).mean()
  File "~/envs/ndpyramid/lib/python3.10/site-packages/datatree/datatree.py", line 292, in __setitem__
    return self._set_item(path, value, new_nodes_along_path=True)
  File "~/envs/ndpyramid/lib/python3.10/site-packages/datatree/treenode.py", line 439, in _set_item
    current_node._set(name, item)
  File "~/envs/ndpyramid/lib/python3.10/site-packages/datatree/datatree.py", line 272, in _set
    raise TypeError(f"Type {type(val)} cannot be assigned to a DataTree")
TypeError: Type <class 'xarray.core.dataset.Dataset'> cannot be assigned to a DataTree
"""
```
I tested this with python 3.10 on a Mac with:
- `xarray.__version__ = '2022.3.0'`
- `ndpyramid.__version__ = '0.0.5'`
- `xarray-datatree = 0.0.5`

**Potential cause**
It seems like the recent API changes of [xarray-datatree](https://xarray-datatree.readthedocs.io/en/latest/whats-new.html#id17) cause this error. With `xarray-datatree` version 0.0.4 the example works 😄

**Comment by jhamman** [comment]
Thanks for the report @observingClouds. We'll need to update ndpyramid to support xarray-datatree 0.0.5.
