### ISSUE TITLE
What standard do ndpyramids conform to?

### ISSUE THREAD

**Issue by TomNicholas** [carbonplan/ndpyramid#78]
My understanding after speaking to @katamartin and @andersy005 yesterday is that the visualization tools expect the pyramids to conform to some "slippy web map tile" standard (or something like that), and that the purpose of this package is to write out Zarr store which basically contain data that conforms to this standard in some way. This info about the standard doesn't seem to be documented anywhere in this package though - have I misunderstood?

**Comment by maxrjones** [comment]
Hi @TomNicholas! You can find some documentation here - https://docs.carbonplan.org/maps/data. Note that page needs some updating after recent maps enhancements (we now support EPSG:4326 as well). We should also add a link to that page from ndpyramid.

We've been talking about formalizing this beyond just our mapping library (e.g., https://github.com/zarr-developers/zarr-specs/issues/125) - let us know if you'd be interested in collaborating on that!

**Comment by TomNicholas** [comment]
Thanks @maxrjones . I guess I'm still a bit confused - that page talks about "adhering to the conventions encoded in the ndpyramid utility", but is that a one-off bespoke format? Did you guys come up with the 128x128 size tiles, and a set of groups of integer multiples of those sizes (i.e. 256x256 for the next resolution up)?

> We've been talking about formalizing this beyond just our mapping library

I think that would be very cool, but probably mostly involves you guys talking to the developers of other visualization libraries (e.g. holoviews) to agree upon a standard.
