### ISSUE TITLE
Document that zlib compression is required

### ISSUE THREAD

**Issue by TomNicholas** [carbonplan/ndpyramid#88]
My understanding is that carbonplan-maps requires the Zarr store to use zlib for compression. Whilst this is the default choice of compression in zarr-python, this requirement isn't documented anywhere in this repo and it probably should be :)

**Comment by maxrjones** [comment]
For V2, I think zlip or gzip are supported based on https://github.com/freeman-lab/zarr-js/blob/5179eea3f23bd8e42af004258f4fc7aa018e6018/src/v2.js#L187-L196. For V3 (which is highly experimental), gzip is the only tested compression. Good point about documenting these requirements!

**Comment by maxrjones** [comment]
Fixed by #89
