### ISSUE TITLE
pyramid_coarsen (or a more generalized function) should allow a custom coarsen func

### ISSUE THREAD

**Issue by ahuang11** [carbonplan/ndpyramid#94]
I think the following:
```python

    for key, factor in enumerate(factors):
        # merge dictionary via union operator
        kwargs |= {d: factor for d in dims}
        plevels[str(key)] = ds.coarsen(**kwargs).mean()
```

Can be generalized:
```python
    for key, factor in enumerate(factors):
        plevels[str(key)] = custom_func(ds, factor)
```

Potential use case, if I want to use [xesmf regrid](https://xesmf.readthedocs.io/en/stable/notebooks/Rectilinear_grid.html) or like [downsample1d operation](https://github.com/holoviz-topics/neuro/issues/87#issuecomment-1908668374)

I'm happy to contribute a PR if this is desired.

**Comment by maxrjones** [comment]
Hi @ahuang11 I wanted to let you know that we'll be having a breakout group on pyramids at the Zarr sprint on Thursday. More details are shared in https://github.com/carbonplan/ndpyramid/issues/101.

I'll try to find time to look in more detail at the two issues you posted this week. On this topic, we already support xesmf regridders through the `pyramid_regrid` function. Is the `downsample1d` operation referenced in the discussion you linked part of holoviews? This approach would be useful if it could help add support pyresampler's downsampling operations (xref https://github.com/carbonplan/ndpyramid/issues/10).

**Comment by ahuang11** [comment]
Thanks for letting me know! I'm at a separate conference right now, but I'll try to attend if I have some spare time!
