### ISSUE TITLE
Factors should be sorted(?)

### ISSUE THREAD

**Issue by ahuang11** [carbonplan/ndpyramid#95]
"The paths to the arrays in dataset series MUST be ordered from largest (i.e. highest resolution) to smallest."

From https://forum.image.sc/t/multiscale-arrays-v0-1/37930

So I think [16, 8, 4, 3, 2, 1] should be reversed.
```python
import xarray as xr
import rioxarray
from ndpyramid import pyramid_coarsen, pyramid_reproject

# load a sample xarray.Dataset
ds = xr.tutorial.load_dataset('air_temperature')

# make a coarsened pyramid
pyramid = pyramid_coarsen(ds, factors=[16, 8, 4, 3, 2, 1], dims=['lat', 'lon'], boundary='trim')

# make a reprojected (EPSG:3857) pyramid
ds = ds.rio.write_crs('EPSG:4326')
pyramid = pyramid_reproject(ds, levels=2)

# write the pyramid to zarr
pyramid.to_zarr('./path/to/write')
```

**Comment by maxrjones** [comment]
Hey @ahuang11, excited to see your interest in ndpyramid! 

ndpyramid doesn't follow the same specification as ome-ngff. See https://github.com/zarr-developers/zarr-specs/issues/125 for some history on where the microscopy and geospatial specs diverged and https://ndpyramid.readthedocs.io/en/latest/schema.html for the ndpyramid schema. @norlandrhagen and I are actually meeting with Sanket and Josh tomorrow to discuss if/how a Zarr spec could accomodate these differences.
